### PR TITLE
Provide default for rufus scheduler

### PR DESCRIPTION
**Pull request by samsm**
Ran into this: https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/426

I toyed with the existing tests but didn't figure out a way to slip this in that I was happy about. So we have what we have here.

### CODE REVIEW

**Comment by samsm** [comment]
LOL I give up

**Comment by marcelolx** [comment]
why? facing some problem with the test?

**Comment by samsm** [comment]
Yeah was having a hard time writing a failing test. Stumped me

**Comment by marcelolx** [comment]
But did you test that your change solves the problem it was trying to solve? We don't have a perfect coverage, so I wouldn't mind if we can't have a test for this line in particular

**Comment by marcelolx** [comment]
Got the test working @samsm. It was just missing the `require 'sidekiq/capsule'`, but I think this probably is not going to solve the problem alone, this seems to be related to https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/419

**Comment by samsm** [comment]
Thanks for tracking that down!

**Pull request closed without merging**
