### PR TITLE
Remove code for Sidekiq < 6.0

### PR DESCRIPTION
**Pull request by y-yagi**
sidekiq-scheduler only supports Sidekiq 6.0 since #411.

### CODE REVIEW

**Comment by y-yagi** [comment]
Hmm. Some tests are failing. I'll check.

**Comment by y-yagi** [comment]
Specs fail randomly. I assume we have some unstable specs.

**Comment by y-yagi** [comment]
> Specs fail randomly. I assume we have some unstable specs.

I created the PR to fix this #444.

**Comment by marcelolx** [comment]
Thanks @y-yagi! Do you mind rebasing?

**Comment by y-yagi** [comment]
Rebased!

**Comment by marcelolx** [comment]
thank you!

**Pull request merged**
