### PR TITLE
[WIP] Allow Sidekiq 7 to work with the gem

### LINKED ISSUE #409: Sidekiq 7.0 support?
I have this error when after upgrading sidekiq to 7.0
```
no implicit conversion of Sidekiq::Config into Hash
```

Backtrace
```
2022-10-14T10:04:34.670Z pid=2228626 tid=1byma INFO: Sidekiq 7.0.0.beta1 connecting to Redis with options {:host=>"localhost", :db=>"0", :size=>1, :pool_name=>"default", :url=>nil}
2022-10-14T10:04:34.673Z pid=2228626 tid=1byma WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2022-10-14T10:04:34.673Z pid=2228626 tid=1byma WARN: TypeError: no implicit conversion of Sidekiq::Config into Hash
2022-10-14T10:04:34.674Z pid=2228626 tid=1byma WARN: lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.3/lib/sidekiq-scheduler/manager.rb:40:in `merge'
lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.3/lib/sidekiq-scheduler/manager.rb:40:in `load_scheduler_options'
lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.3/lib/sidekiq-scheduler/manager.rb:21:in `initialize'
lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.3/lib/sidekiq-scheduler.rb:21:in `new'
lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.3/lib/sidekiq-scheduler.rb:21:in `block (2 levels) in <main>'
lib/ruby/gems/3.1.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:58:in `block in fire_event'
lib/ruby/gems/3.1.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:57:in `each'
lib/ruby/gems/3.1.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:57:in `fire_event'
lib/ruby/gems/3.1.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/cli.rb:105:in `run'
lib/ruby/gems/3.1.0/gems/sidekiq-7.0.0.beta1/bin/sidekiq:31:in `<top (required)>'
bin/sidekiq:25:in `load'
```

### PR DESCRIPTION
**Pull request by t27duck**
Closes #409 

- Updated the sidekiq dependency in the gemspec.
- Changed the redis gem to be a development dependency.
- Added `SIDEKIQ_GTE_7_0_0` for version checks.
- Implemented changes needed to get sidekiq 7 playing nice using the new constant to fork logic.

I used a near vanilla Rails app with some simple jobs to verify sidekiq boots and scheduled jobs do enqueue and execute.

### CODE REVIEW

**Comment by t27duck** [comment]
So with the release of Sidekiq 7, Sidekiq 5.x and earlier is no longer supported. We may want to take this opportunity to also drop support for those Sidekiq versions in this gem as well here. Maybe also dropping EOL Rubies?

I wouldn't mind taking a shot and a better wrapper class of some sort in this PR to encapsulate pulling out the sidekiq options as a hash instead of having it in riddled if statements. Another option could be to determine exactly what sidekiq options this gem cares about instead of passing around the whole config and merging things blindly just in case we need something.

**Comment by marcelolx** [comment]
> So with the release of Sidekiq 7, Sidekiq 5.x and earlier is no longer supported. We may want to take this opportunity to also drop support for those Sidekiq versions in this gem as well here. Maybe also dropping EOL Rubies?

Yes, let's do that. Is it needed for this PR or can we do it in a separate one?

**Comment by marcelolx** [comment]
> I wouldn't mind taking a shot and a better wrapper class of some sort in this PR to encapsulate pulling out the sidekiq options as a hash instead of having it in riddled if statements. Another option could be to determine exactly what sidekiq options this gem cares about instead of passing around the whole config and merging things blindly just in case we need something.

I haven't touched the gem in a while, but I remember I did want to do something similar, if we can do it, it would be lovely. 

I'll see if I can take some time to take a stab on it too

**Comment by marcelolx** [comment]
@t27duck I pushed some commits, tests are all fixed for both sidekiq 6 & 7, we're just down a bit on the coverage. 

I still want us to try to wrap the sidekiq options in a wrapper class so we can avoid all those ifs as you suggested.

**Comment by t27duck** [comment]
Sounds good. I'm going to try to carve out some time to take a swing at something (either a wrapper class or some conditional method overriding mixins) either Friday evening or sometime Saturday (I'm on US east coast time).

**Comment by marcelolx** [comment]
@t27duck I took a stab at it here https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/412

I think we can work on the refactor from there, feel free to work on that branch or come up with a different approach.

I'll merge this branch here but won't make a release until we get that refactor in.

**Comment by palexvs** [comment]
@marcelolx could you release a new version that supports Sidekiq 7, please?

**Comment by marcelolx** [comment]
@palexvs While we don't drop a new release you can do the following to use sidekiq-scheduler with sidekiq 7 https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/409#issuecomment-1303233347, my plans are to push https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/412 to the finish line next week, but until that, you can safely point your gemfile to the github repo and use sidekiq-scheduler with Sidekiq 7

**Pull request merged**
